// ============================================================
//  Disha for India — Comprehensive Mock Data
//  All seed data consumed by service-layer functions.
// ============================================================

/* ------------------------------------------------------------------ */
/*  PROGRAMS                                                           */
/* ------------------------------------------------------------------ */
export const programs = [
  {
    id: 'prog-001',
    title: 'Digital Literacy Camp',
    category: 'Tech',
    description:
      'A six-week immersive camp that empowers rural communities across Rajasthan with foundational digital skills — from smartphone usage and UPI payments to basic internet safety and government e-services. Volunteers conduct hands-on workshops in village schools and panchayat halls, using vernacular-language materials developed by our content team. The program has reached over 12,000 beneficiaries since inception and was featured in the Hindustan Times as a model grassroots tech initiative.',
    shortDesc:
      'Empowering rural Rajasthan with foundational digital skills through interactive workshops.',
    location: 'Jaipur & surrounding districts, Rajasthan',
    coordinator: {
      name: 'Priya Mehta',
      email: 'priya.mehta@dishaindia.org',
      phone: '+91-98765-43210',
      avatar: 'PM',
    },
    bannerColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    startDate: '2026-07-15',
    endDate: '2026-08-26',
    deadline: '2026-07-10',
    totalVolunteers: 40,
    currentVolunteers: 27,
    hoursRequired: 60,
    skills: ['Teaching', 'Communication', 'Basic IT', 'Hindi / Rajasthani'],
    tags: ['Rural', 'Tech', 'Education', 'Featured'],
    status: 'open',
    difficulty: 'beginner',
    isPopular: true,
    organizer: 'Disha Foundation — Tech for Bharat Cell',
  },
  {
    id: 'prog-002',
    title: 'Urban Reforestation Drive',
    category: 'Environment',
    description:
      'Delhi\'s green cover has shrunk by 40% in two decades. This program mobilises volunteers to plant and nurture native-species saplings across 15 identified degraded urban plots, road medians, and school grounds in West Delhi. Volunteers receive training in soil preparation, drip-irrigation setup, and long-term sapling care. Monthly monitoring visits ensure survival rates stay above 80%. The 2025 cohort planted 8,400 trees; this season targets 12,000.',
    shortDesc:
      'Planting and nurturing 12,000 native saplings across degraded urban plots in West Delhi.',
    location: 'West Delhi, Delhi NCR',
    coordinator: {
      name: 'Arjun Kapoor',
      email: 'arjun.kapoor@dishaindia.org',
      phone: '+91-99887-76655',
      avatar: 'AK',
    },
    bannerColor: 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)',
    startDate: '2026-08-01',
    endDate: '2026-10-31',
    deadline: '2026-07-25',
    totalVolunteers: 60,
    currentVolunteers: 52,
    hoursRequired: 48,
    skills: ['Physical Fitness', 'Landscaping', 'Environmental Awareness'],
    tags: ['Environment', 'Green Delhi', 'Outdoor', 'Popular'],
    status: 'open',
    difficulty: 'beginner',
    isPopular: true,
    organizer: 'Disha Foundation — Green Missions Wing',
  },
  {
    id: 'prog-003',
    title: 'Mobile Health Clinic',
    category: 'Health',
    description:
      'Partnering with three government hospitals in Pune, this program deploys mobile medical vans to underserved slum communities every weekend. Volunteers assist qualified doctors and nurses in patient registration, vital-signs screening, medicine distribution, and health education sessions covering maternal health, nutrition, and sanitation. Prior healthcare background is preferred but not mandatory — all volunteers receive a two-day orientation. Each camp serves 150–200 patients.',
    shortDesc:
      'Weekend mobile clinics bringing free medical care to underserved Pune communities.',
    location: 'Hadapsar, Kondhwa & Bibwewadi, Pune',
    coordinator: {
      name: 'Dr. Sunita Rao',
      email: 'sunita.rao@dishaindia.org',
      phone: '+91-94567-89012',
      avatar: 'SR',
    },
    bannerColor: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    startDate: '2026-07-05',
    endDate: '2026-12-28',
    deadline: '2026-06-30',
    totalVolunteers: 35,
    currentVolunteers: 35,
    hoursRequired: 80,
    skills: ['Healthcare', 'Patient Care', 'First Aid', 'Marathi / Hindi'],
    tags: ['Health', 'Medical', 'Weekend', 'Full'],
    status: 'closed',
    difficulty: 'intermediate',
    isPopular: false,
    organizer: 'Disha Foundation — Health for All Division',
  },
  {
    id: 'prog-004',
    title: 'Women Empowerment Workshop',
    category: 'Community',
    description:
      'A transformative 10-week skill-building series for women aged 18–45 in low-income neighbourhoods of Hyderabad. Modules cover financial literacy, legal rights awareness, digital banking, entrepreneurship basics, and self-defence. Volunteer facilitators co-deliver sessions alongside trained counsellors. Graduates receive a certificate recognised by the Telangana State Government and access to a micro-credit network. The 2025 batch had a 94% completion rate and 60% of graduates started small businesses within six months.',
    shortDesc:
      'Ten-week skill-building and empowerment series for women in Hyderabad\'s low-income areas.',
    location: 'Mehdipatnam & Malakpet, Hyderabad',
    coordinator: {
      name: 'Kavitha Nair',
      email: 'kavitha.nair@dishaindia.org',
      phone: '+91-97654-32109',
      avatar: 'KN',
    },
    bannerColor: 'linear-gradient(135deg, #fccb90 0%, #d57eeb 100%)',
    startDate: '2026-09-01',
    endDate: '2026-11-10',
    deadline: '2026-08-20',
    totalVolunteers: 25,
    currentVolunteers: 8,
    hoursRequired: 100,
    skills: ['Counselling', 'Financial Literacy', 'Telugu / Hindi', 'Public Speaking'],
    tags: ['Women', 'Empowerment', 'Upcoming', 'Government-Backed'],
    status: 'upcoming',
    difficulty: 'intermediate',
    isPopular: false,
    organizer: 'Disha Foundation — Community Development Unit',
  },
  {
    id: 'prog-005',
    title: 'Clean River Initiative',
    category: 'Environment',
    description:
      'The Sabarmati River in Ahmedabad carries an alarming load of industrial effluents and domestic waste. This initiative organises fortnightly riverbank clean-up drives, installs floating trash barriers at two key ghats, and runs community awareness campaigns in 20 adjoining wards. Volunteers also collect water samples for a citizen-science pollution-monitoring database. The program works in close coordination with the Ahmedabad Municipal Corporation and Gujarat Pollution Control Board.',
    shortDesc:
      'Cleaning the Sabarmati riverbanks and building community-led pollution monitoring in Ahmedabad.',
    location: 'Riverfront Ghats, Ahmedabad, Gujarat',
    coordinator: {
      name: 'Rohan Shah',
      email: 'rohan.shah@dishaindia.org',
      phone: '+91-98236-54701',
      avatar: 'RS',
    },
    bannerColor: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    startDate: '2026-08-15',
    endDate: '2027-02-28',
    deadline: '2026-08-10',
    totalVolunteers: 50,
    currentVolunteers: 14,
    hoursRequired: 72,
    skills: ['Environmental Science', 'Data Collection', 'Community Outreach', 'Gujarati'],
    tags: ['Environment', 'River', 'Citizen Science', 'Municipal'],
    status: 'upcoming',
    difficulty: 'beginner',
    isPopular: false,
    organizer: 'Disha Foundation — Clean Water Task Force',
  },
  {
    id: 'prog-006',
    title: 'Youth Coding Bootcamp',
    category: 'Tech',
    description:
      'An intensive eight-week coding bootcamp for underprivileged students aged 14–20 in Mumbai\'s Dharavi and Kurla communities. Volunteer mentors — software professionals and college students — teach HTML/CSS, Python fundamentals, and basic web development through project-based learning. Each cohort of 30 students builds a portfolio project by graduation. Alumni of the 2024 batch include three students who won national-level hackathons and two who received internship offers from Pune-based startups.',
    shortDesc:
      'Eight-week coding bootcamp turning Mumbai\'s underprivileged youth into junior developers.',
    location: 'Dharavi & Kurla, Mumbai, Maharashtra',
    coordinator: {
      name: 'Neha Joshi',
      email: 'neha.joshi@dishaindia.org',
      phone: '+91-91234-56789',
      avatar: 'NJ',
    },
    bannerColor: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
    startDate: '2026-07-20',
    endDate: '2026-09-14',
    deadline: '2026-07-15',
    totalVolunteers: 30,
    currentVolunteers: 22,
    hoursRequired: 90,
    skills: ['Python', 'Web Development', 'Mentoring', 'Marathi / Hindi'],
    tags: ['Tech', 'Youth', 'Coding', 'Featured', 'Popular'],
    status: 'open',
    difficulty: 'advanced',
    isPopular: true,
    organizer: 'Disha Foundation — Digital Youth Corps',
  },
];

/* ------------------------------------------------------------------ */
/*  APPLICATIONS                                                       */
/* ------------------------------------------------------------------ */
export const applications = [
  {
    id: 'app-001',
    programId: 'prog-001',
    programTitle: 'Digital Literacy Camp',
    programCategory: 'Tech',
    programLocation: 'Jaipur & surrounding districts, Rajasthan',
    organizerName: 'Disha Foundation — Tech for Bharat Cell',
    bannerColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    appliedDate: '2026-06-20',
    status: 'approved',
    coordinatorName: 'Priya Mehta',
    coordinatorEmail: 'priya.mehta@dishaindia.org',
    coordinatorNotes:
      'Your application has been reviewed. Welcome aboard! Please attend the mandatory orientation on 12 July at 10 AM at the Jaipur HQ.',
    deadline: '2026-07-10',
    motivationStatement:
      'I strongly believe that digital access is a fundamental right. Having grown up in a semi-urban area myself, I understand the barriers rural communities face. I want to use my IT background to create tangible impact.',
    skills: ['Teaching', 'Basic IT', 'Hindi'],
    timeline: [
      { stage: 'Application Submitted', date: '2026-06-20', note: 'Form submitted online.', done: true },
      { stage: 'Under Review', date: '2026-06-22', note: 'Coordinator reviewing your profile.', done: true },
      { stage: 'Approved', date: '2026-06-25', note: 'Congratulations! Application approved.', done: true },
      { stage: 'Orientation', date: '2026-07-12', note: 'Mandatory orientation session at Jaipur HQ.', done: false },
      { stage: 'Program Start', date: '2026-07-15', note: 'Camp begins at village schools.', done: false },
    ],
    documents: ['Resume_Aditya_Kumar.pdf', 'ID_Proof_Aditya.pdf'],
  },
  {
    id: 'app-002',
    programId: 'prog-006',
    programTitle: 'Youth Coding Bootcamp',
    programCategory: 'Tech',
    programLocation: 'Dharavi & Kurla, Mumbai, Maharashtra',
    organizerName: 'Disha Foundation — Digital Youth Corps',
    bannerColor: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
    appliedDate: '2026-06-28',
    status: 'under_review',
    coordinatorName: 'Neha Joshi',
    coordinatorEmail: 'neha.joshi@dishaindia.org',
    coordinatorNotes: 'Your application is currently under review. We will contact you by 10 July.',
    deadline: '2026-07-15',
    motivationStatement:
      'As a software engineer with 4 years of experience, I want to give back by mentoring the next generation of coders from underserved communities. Project-based learning is something I am passionate about.',
    skills: ['Python', 'Web Development', 'Mentoring'],
    timeline: [
      { stage: 'Application Submitted', date: '2026-06-28', note: 'Form submitted online.', done: true },
      { stage: 'Under Review', date: '2026-06-30', note: 'Coordinator reviewing your profile.', done: true },
      { stage: 'Approved', date: '', note: 'Awaiting approval decision.', done: false },
      { stage: 'Orientation', date: '2026-07-18', note: 'Orientation at Mumbai office.', done: false },
      { stage: 'Program Start', date: '2026-07-20', note: 'Bootcamp begins.', done: false },
    ],
    documents: ['Resume_Aditya_Kumar.pdf'],
  },
  {
    id: 'app-003',
    programId: 'prog-002',
    programTitle: 'Urban Reforestation Drive',
    programCategory: 'Environment',
    programLocation: 'West Delhi, Delhi NCR',
    organizerName: 'Disha Foundation — Green Missions Wing',
    bannerColor: 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)',
    appliedDate: '2026-06-10',
    status: 'approved',
    coordinatorName: 'Arjun Kapoor',
    coordinatorEmail: 'arjun.kapoor@dishaindia.org',
    coordinatorNotes:
      'Welcome to Team Green! Your first session is on 2 August at Tilak Nagar Park. Please wear comfortable outdoor clothing.',
    deadline: '2026-07-25',
    motivationStatement:
      'The Delhi smog crisis has personally affected my family. I want to be part of a concrete solution by contributing my weekends to planting trees and raising community awareness.',
    skills: ['Physical Fitness', 'Environmental Awareness'],
    timeline: [
      { stage: 'Application Submitted', date: '2026-06-10', note: 'Form submitted online.', done: true },
      { stage: 'Under Review', date: '2026-06-12', note: 'Coordinator reviewing your profile.', done: true },
      { stage: 'Approved', date: '2026-06-15', note: 'Application approved.', done: true },
      { stage: 'Orientation', date: '2026-07-28', note: 'Training on sapling care and soil prep.', done: false },
      { stage: 'Program Start', date: '2026-08-01', note: 'First planting session.', done: false },
    ],
    documents: ['Resume_Aditya_Kumar.pdf', 'ID_Proof_Aditya.pdf'],
  },
  {
    id: 'app-004',
    programId: 'prog-003',
    programTitle: 'Mobile Health Clinic',
    programCategory: 'Health',
    programLocation: 'Hadapsar, Kondhwa & Bibwewadi, Pune',
    organizerName: 'Disha Foundation — Health for All Division',
    bannerColor: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    appliedDate: '2026-05-30',
    status: 'rejected',
    coordinatorName: 'Dr. Sunita Rao',
    coordinatorEmail: 'sunita.rao@dishaindia.org',
    coordinatorNotes:
      'Thank you for your interest. Unfortunately, all volunteer slots have been filled. We encourage you to apply to our next health initiative launching in Q4 2026.',
    deadline: '2026-06-30',
    motivationStatement:
      'I am a final-year pharmacy student and want to apply my knowledge in a real-world community-health setting. I am comfortable with patient interaction in both Hindi and Marathi.',
    skills: ['Healthcare', 'First Aid', 'Marathi'],
    timeline: [
      { stage: 'Application Submitted', date: '2026-05-30', note: 'Form submitted online.', done: true },
      { stage: 'Under Review', date: '2026-06-01', note: 'Coordinator reviewing your profile.', done: true },
      { stage: 'Rejected', date: '2026-06-05', note: 'Slots filled; application not accepted.', done: true },
      { stage: 'Program Start', date: '2026-07-05', note: 'Program already started.', done: false },
    ],
    documents: ['Resume_Aditya_Kumar.pdf', 'Pharmacy_Enrollment_Certificate.pdf'],
  },
  {
    id: 'app-005',
    programId: 'prog-004',
    programTitle: 'Women Empowerment Workshop',
    programCategory: 'Community',
    programLocation: 'Mehdipatnam & Malakpet, Hyderabad',
    organizerName: 'Disha Foundation — Community Development Unit',
    bannerColor: 'linear-gradient(135deg, #fccb90 0%, #d57eeb 100%)',
    appliedDate: '2026-07-01',
    status: 'pending',
    coordinatorName: 'Kavitha Nair',
    coordinatorEmail: 'kavitha.nair@dishaindia.org',
    coordinatorNotes: '',
    deadline: '2026-08-20',
    motivationStatement:
      'Having worked as a microfinance field officer for two years, I have seen the transformative power of financial literacy for women firsthand. I want to channel that experience into facilitation and community education.',
    skills: ['Financial Literacy', 'Telugu', 'Counselling'],
    timeline: [
      { stage: 'Application Submitted', date: '2026-07-01', note: 'Form submitted online.', done: true },
      { stage: 'Under Review', date: '', note: 'Awaiting review.', done: false },
      { stage: 'Approved / Rejected', date: '', note: 'Pending coordinator decision.', done: false },
      { stage: 'Orientation', date: '2026-08-25', note: 'Planned orientation date.', done: false },
      { stage: 'Program Start', date: '2026-09-01', note: 'Workshop series begins.', done: false },
    ],
    documents: ['Resume_Aditya_Kumar.pdf'],
  },
  {
    id: 'app-006',
    programId: 'prog-005',
    programTitle: 'Clean River Initiative',
    programCategory: 'Environment',
    programLocation: 'Riverfront Ghats, Ahmedabad, Gujarat',
    organizerName: 'Disha Foundation — Clean Water Task Force',
    bannerColor: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    appliedDate: '2026-06-15',
    status: 'waitlisted',
    coordinatorName: 'Rohan Shah',
    coordinatorEmail: 'rohan.shah@dishaindia.org',
    coordinatorNotes:
      'You are currently on the waitlist. If a slot opens up, we will notify you within 48 hours. Thank you for your patience.',
    deadline: '2026-08-10',
    motivationStatement:
      'The Sabarmati holds cultural significance for every Gujarati. I want to actively contribute to restoring its health through clean-up drives and citizen-science data collection.',
    skills: ['Environmental Science', 'Data Collection', 'Gujarati'],
    timeline: [
      { stage: 'Application Submitted', date: '2026-06-15', note: 'Form submitted online.', done: true },
      { stage: 'Under Review', date: '2026-06-17', note: 'Coordinator reviewing your profile.', done: true },
      { stage: 'Waitlisted', date: '2026-06-20', note: 'Placed on waitlist due to high demand.', done: true },
      { stage: 'Confirmed / Declined', date: '', note: 'Awaiting slot availability.', done: false },
      { stage: 'Program Start', date: '2026-08-15', note: 'Initiative begins.', done: false },
    ],
    documents: ['Resume_Aditya_Kumar.pdf', 'ID_Proof_Aditya.pdf'],
  },
  {
    id: 'app-007',
    programId: 'prog-006',
    programTitle: 'Youth Coding Bootcamp',
    programCategory: 'Tech',
    programLocation: 'Dharavi & Kurla, Mumbai, Maharashtra',
    organizerName: 'Disha Foundation — Digital Youth Corps',
    bannerColor: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
    appliedDate: '2026-05-05',
    status: 'approved',
    coordinatorName: 'Neha Joshi',
    coordinatorEmail: 'neha.joshi@dishaindia.org',
    coordinatorNotes:
      'Your application has been approved. You are assigned to the Python stream. Please review the curriculum document shared via email.',
    deadline: '2026-07-15',
    motivationStatement:
      'Coding changed my life. I want to pass that opportunity to students who would otherwise never have access to quality tech education.',
    skills: ['Python', 'Mentoring'],
    timeline: [
      { stage: 'Application Submitted', date: '2026-05-05', note: 'Form submitted online.', done: true },
      { stage: 'Under Review', date: '2026-05-07', note: 'Coordinator reviewed profile.', done: true },
      { stage: 'Approved', date: '2026-05-10', note: 'Application approved.', done: true },
      { stage: 'Orientation', date: '2026-07-18', note: 'Completed.', done: true },
      { stage: 'Program Start', date: '2026-07-20', note: 'Bootcamp started.', done: false },
    ],
    documents: ['Resume_Aditya_Kumar.pdf', 'Portfolio_Link.txt'],
  },
  {
    id: 'app-008',
    programId: 'prog-001',
    programTitle: 'Digital Literacy Camp',
    programCategory: 'Tech',
    programLocation: 'Jaipur & surrounding districts, Rajasthan',
    organizerName: 'Disha Foundation — Tech for Bharat Cell',
    bannerColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    appliedDate: '2026-04-18',
    status: 'approved',
    coordinatorName: 'Priya Mehta',
    coordinatorEmail: 'priya.mehta@dishaindia.org',
    coordinatorNotes: 'Great to have you again! Your previous cohort experience is valuable.',
    deadline: '2026-07-10',
    motivationStatement:
      'This is my second time applying for this program. The first cycle was incredibly rewarding and I want to continue mentoring the next batch of rural learners.',
    skills: ['Teaching', 'Basic IT', 'Hindi', 'Rajasthani'],
    timeline: [
      { stage: 'Application Submitted', date: '2026-04-18', note: 'Form submitted online.', done: true },
      { stage: 'Under Review', date: '2026-04-20', note: 'Fast-tracked due to prior experience.', done: true },
      { stage: 'Approved', date: '2026-04-22', note: 'Application approved.', done: true },
      { stage: 'Orientation', date: '2026-07-12', note: 'Orientation at Jaipur HQ.', done: false },
      { stage: 'Program Start', date: '2026-07-15', note: 'Camp begins.', done: false },
    ],
    documents: ['Resume_Aditya_Kumar.pdf'],
  },
];

/* ------------------------------------------------------------------ */
/*  JOINED PROGRAMS                                                    */
/* ------------------------------------------------------------------ */
export const joinedPrograms = [
  {
    id: 'join-001',
    programId: 'prog-001',
    programTitle: 'Digital Literacy Camp',
    programCategory: 'Tech',
    coordinatorName: 'Priya Mehta',
    coordinatorEmail: 'priya.mehta@dishaindia.org',
    bannerColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    joinedDate: '2026-06-25',
    endDate: '2026-08-26',
    totalHoursRequired: 60,
    hoursCompleted: 18,
    attendancePercent: 75,
    totalSessions: 12,
    attendedSessions: 9,
    certificateProgress: 30,
    rewardsEarned: 180,
    status: 'active',
    nextSession: { date: '2026-07-05', time: '09:00 AM', location: 'Sanganer Village School' },
  },
  {
    id: 'join-002',
    programId: 'prog-002',
    programTitle: 'Urban Reforestation Drive',
    programCategory: 'Environment',
    coordinatorName: 'Arjun Kapoor',
    coordinatorEmail: 'arjun.kapoor@dishaindia.org',
    bannerColor: 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)',
    joinedDate: '2026-06-15',
    endDate: '2026-10-31',
    totalHoursRequired: 48,
    hoursCompleted: 12,
    attendancePercent: 80,
    totalSessions: 10,
    attendedSessions: 8,
    certificateProgress: 25,
    rewardsEarned: 120,
    status: 'active',
    nextSession: { date: '2026-07-06', time: '06:30 AM', location: 'Tilak Nagar Park, West Delhi' },
  },
  {
    id: 'join-003',
    programId: 'prog-006',
    programTitle: 'Youth Coding Bootcamp',
    programCategory: 'Tech',
    coordinatorName: 'Neha Joshi',
    coordinatorEmail: 'neha.joshi@dishaindia.org',
    bannerColor: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
    joinedDate: '2026-05-10',
    endDate: '2026-06-14',
    totalHoursRequired: 90,
    hoursCompleted: 90,
    attendancePercent: 96,
    totalSessions: 24,
    attendedSessions: 23,
    certificateProgress: 100,
    rewardsEarned: 900,
    status: 'completed',
    nextSession: null,
  },
  {
    id: 'join-004',
    programId: 'prog-005',
    programTitle: 'Clean River Initiative',
    programCategory: 'Environment',
    coordinatorName: 'Rohan Shah',
    coordinatorEmail: 'rohan.shah@dishaindia.org',
    bannerColor: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    joinedDate: '2026-06-20',
    endDate: '2027-02-28',
    totalHoursRequired: 72,
    hoursCompleted: 6,
    attendancePercent: 66,
    totalSessions: 6,
    attendedSessions: 4,
    certificateProgress: 8,
    rewardsEarned: 60,
    status: 'active',
    nextSession: { date: '2026-07-12', time: '07:00 AM', location: 'Sabarmati Riverfront, Gate 3' },
  },
];

/* ------------------------------------------------------------------ */
/*  ATTENDANCE RECORDS                                                 */
/* ------------------------------------------------------------------ */
export const attendanceRecords = [
  {
    id: 'att-001',
    programId: 'prog-001',
    programTitle: 'Digital Literacy Camp',
    date: '2026-07-01',
    checkInTime: '09:02 AM',
    checkOutTime: '01:05 PM',
    hoursWorked: 4.0,
    status: 'present',
    coordinatorName: 'Priya Mehta',
    location: 'Sanganer Village School',
    notes: 'Taught UPI and Google Pay usage to 35 participants.',
  },
  {
    id: 'att-002',
    programId: 'prog-001',
    programTitle: 'Digital Literacy Camp',
    date: '2026-06-28',
    checkInTime: '09:15 AM',
    checkOutTime: '01:10 PM',
    hoursWorked: 3.9,
    status: 'late',
    coordinatorName: 'Priya Mehta',
    location: 'Chomu Block Panchayat Hall',
    notes: 'Late due to transport delay. Session on internet safety delivered.',
  },
  {
    id: 'att-003',
    programId: 'prog-001',
    programTitle: 'Digital Literacy Camp',
    date: '2026-06-24',
    checkInTime: '09:00 AM',
    checkOutTime: '01:00 PM',
    hoursWorked: 4.0,
    status: 'present',
    coordinatorName: 'Priya Mehta',
    location: 'Sanganer Village School',
    notes: 'Smartphone basics — camera, contacts, and settings modules.',
  },
  {
    id: 'att-004',
    programId: 'prog-001',
    programTitle: 'Digital Literacy Camp',
    date: '2026-06-20',
    checkInTime: '',
    checkOutTime: '',
    hoursWorked: 0,
    status: 'absent',
    coordinatorName: 'Priya Mehta',
    location: 'Chomu Block Panchayat Hall',
    notes: 'Medical leave.',
  },
  {
    id: 'att-005',
    programId: 'prog-001',
    programTitle: 'Digital Literacy Camp',
    date: '2026-06-17',
    checkInTime: '09:05 AM',
    checkOutTime: '01:08 PM',
    hoursWorked: 4.0,
    status: 'present',
    coordinatorName: 'Priya Mehta',
    location: 'Sanganer Village School',
    notes: 'Government e-services — Jan Dhan portal demo.',
  },
  {
    id: 'att-006',
    programId: 'prog-002',
    programTitle: 'Urban Reforestation Drive',
    date: '2026-06-29',
    checkInTime: '06:35 AM',
    checkOutTime: '10:40 AM',
    hoursWorked: 4.1,
    status: 'present',
    coordinatorName: 'Arjun Kapoor',
    location: 'Tilak Nagar Park, West Delhi',
    notes: 'Planted 120 saplings; set up two drip lines.',
  },
  {
    id: 'att-007',
    programId: 'prog-002',
    programTitle: 'Urban Reforestation Drive',
    date: '2026-06-22',
    checkInTime: '06:30 AM',
    checkOutTime: '10:35 AM',
    hoursWorked: 4.1,
    status: 'present',
    coordinatorName: 'Arjun Kapoor',
    location: 'Tilak Nagar Park, West Delhi',
    notes: 'Soil preparation and sapling care training.',
  },
  {
    id: 'att-008',
    programId: 'prog-002',
    programTitle: 'Urban Reforestation Drive',
    date: '2026-06-15',
    checkInTime: '06:30 AM',
    checkOutTime: '09:30 AM',
    hoursWorked: 3.0,
    status: 'present',
    coordinatorName: 'Arjun Kapoor',
    location: 'Punjabi Bagh Road Median',
    notes: 'First session — orientation and introductory planting.',
  },
  {
    id: 'att-009',
    programId: 'prog-006',
    programTitle: 'Youth Coding Bootcamp',
    date: '2026-06-10',
    checkInTime: '10:00 AM',
    checkOutTime: '02:00 PM',
    hoursWorked: 4.0,
    status: 'present',
    coordinatorName: 'Neha Joshi',
    location: 'Dharavi Community Centre',
    notes: 'Python loops and functions — 12 students completed Module 4.',
  },
  {
    id: 'att-010',
    programId: 'prog-006',
    programTitle: 'Youth Coding Bootcamp',
    date: '2026-06-07',
    checkInTime: '10:00 AM',
    checkOutTime: '02:05 PM',
    hoursWorked: 4.1,
    status: 'present',
    coordinatorName: 'Neha Joshi',
    location: 'Dharavi Community Centre',
    notes: 'Introduction to Python data types.',
  },
  {
    id: 'att-011',
    programId: 'prog-006',
    programTitle: 'Youth Coding Bootcamp',
    date: '2026-06-03',
    checkInTime: '10:00 AM',
    checkOutTime: '02:00 PM',
    hoursWorked: 4.0,
    status: 'present',
    coordinatorName: 'Neha Joshi',
    location: 'Dharavi Community Centre',
    notes: 'HTML/CSS portfolio projects reviewed.',
  },
  {
    id: 'att-012',
    programId: 'prog-006',
    programTitle: 'Youth Coding Bootcamp',
    date: '2026-05-31',
    checkInTime: '10:20 AM',
    checkOutTime: '02:00 PM',
    hoursWorked: 3.7,
    status: 'late',
    coordinatorName: 'Neha Joshi',
    location: 'Kurla Community Hall',
    notes: 'Late due to local train delay. Covered CSS Flexbox.',
  },
  {
    id: 'att-013',
    programId: 'prog-006',
    programTitle: 'Youth Coding Bootcamp',
    date: '2026-05-27',
    checkInTime: '10:00 AM',
    checkOutTime: '02:00 PM',
    hoursWorked: 4.0,
    status: 'present',
    coordinatorName: 'Neha Joshi',
    location: 'Dharavi Community Centre',
    notes: 'HTML basics and intro to web browsers.',
  },
  {
    id: 'att-014',
    programId: 'prog-006',
    programTitle: 'Youth Coding Bootcamp',
    date: '2026-05-24',
    checkInTime: '',
    checkOutTime: '',
    hoursWorked: 0,
    status: 'excused',
    coordinatorName: 'Neha Joshi',
    location: 'Dharavi Community Centre',
    notes: 'Prior notice given for family function.',
  },
  {
    id: 'att-015',
    programId: 'prog-005',
    programTitle: 'Clean River Initiative',
    date: '2026-06-28',
    checkInTime: '07:05 AM',
    checkOutTime: '10:10 AM',
    hoursWorked: 3.1,
    status: 'present',
    coordinatorName: 'Rohan Shah',
    location: 'Sabarmati Riverfront, Gate 3',
    notes: 'Collected 8 water samples and removed 200 kg of debris.',
  },
  {
    id: 'att-016',
    programId: 'prog-005',
    programTitle: 'Clean River Initiative',
    date: '2026-06-21',
    checkInTime: '07:00 AM',
    checkOutTime: '10:05 AM',
    hoursWorked: 3.1,
    status: 'present',
    coordinatorName: 'Rohan Shah',
    location: 'Sabarmati Riverfront, Gate 1',
    notes: 'Installed first floating trash barrier.',
  },
  {
    id: 'att-017',
    programId: 'prog-005',
    programTitle: 'Clean River Initiative',
    date: '2026-06-14',
    checkInTime: '07:00 AM',
    checkOutTime: '09:45 AM',
    hoursWorked: 2.8,
    status: 'present',
    coordinatorName: 'Rohan Shah',
    location: 'Sabarmati Riverfront, Gate 3',
    notes: 'Orientation session and first clean-up drive.',
  },
  {
    id: 'att-018',
    programId: 'prog-005',
    programTitle: 'Clean River Initiative',
    date: '2026-06-07',
    checkInTime: '',
    checkOutTime: '',
    hoursWorked: 0,
    status: 'absent',
    coordinatorName: 'Rohan Shah',
    location: 'Sabarmati Riverfront, Gate 3',
    notes: 'No-show. Coordinator attempted contact.',
  },
  {
    id: 'att-019',
    programId: 'prog-001',
    programTitle: 'Digital Literacy Camp',
    date: '2026-06-10',
    checkInTime: '09:00 AM',
    checkOutTime: '01:00 PM',
    hoursWorked: 4.0,
    status: 'present',
    coordinatorName: 'Priya Mehta',
    location: 'Sanganer Village School',
    notes: 'Session on e-governance — DigiLocker and UMANG apps.',
  },
  {
    id: 'att-020',
    programId: 'prog-002',
    programTitle: 'Urban Reforestation Drive',
    date: '2026-06-08',
    checkInTime: '06:30 AM',
    checkOutTime: '10:30 AM',
    hoursWorked: 4.0,
    status: 'present',
    coordinatorName: 'Arjun Kapoor',
    location: 'Rajouri Garden Greenbelt',
    notes: 'Native species identification and planting techniques workshop.',
  },
];

/* ------------------------------------------------------------------ */
/*  VOLUNTEER HOURS STATS                                              */
/* ------------------------------------------------------------------ */
export const volunteerHoursStats = {
  today: 4.0,
  thisWeek: 12.0,
  thisMonth: 36.2,
  thisYear: 126.0,
  lifetime: 354.5,
  weeklyData: [
    { day: 'Mon', hours: 4.0 },
    { day: 'Tue', hours: 0 },
    { day: 'Wed', hours: 4.1 },
    { day: 'Thu', hours: 0 },
    { day: 'Fri', hours: 3.9 },
    { day: 'Sat', hours: 0 },
    { day: 'Sun', hours: 0 },
  ],
  monthlyData: [
    { month: 'Feb', hours: 18 },
    { month: 'Mar', hours: 24 },
    { month: 'Apr', hours: 30 },
    { month: 'May', hours: 28 },
    { month: 'Jun', hours: 36 },
    { month: 'Jul', hours: 12 },
  ],
  programBreakdown: [
    { program: 'Digital Literacy Camp', hours: 18, color: '#667eea' },
    { program: 'Urban Reforestation Drive', hours: 12, color: '#11998e' },
    { program: 'Youth Coding Bootcamp', hours: 90, color: '#fa709a' },
    { program: 'Clean River Initiative', hours: 6, color: '#4facfe' },
  ],
  streakDays: 5,
  recentSessions: [
    { date: '2026-07-01', program: 'Digital Literacy Camp', hours: 4.0, location: 'Sanganer Village School' },
    { date: '2026-06-29', program: 'Urban Reforestation Drive', hours: 4.1, location: 'Tilak Nagar Park' },
    { date: '2026-06-28', program: 'Digital Literacy Camp', hours: 3.9, location: 'Chomu Block Panchayat Hall' },
    { date: '2026-06-22', program: 'Urban Reforestation Drive', hours: 4.1, location: 'Tilak Nagar Park' },
    { date: '2026-06-21', program: 'Clean River Initiative', hours: 3.1, location: 'Sabarmati Riverfront' },
  ],
};

/* ------------------------------------------------------------------ */
/*  ADMIN — APPLICATION STATS                                         */
/* ------------------------------------------------------------------ */
export const adminApplicationStats = {
  pending: 14,
  approved: 87,
  rejected: 12,
  waitlisted: 9,
  today: 5,
  newVolunteers: 23,
  recentApplications: [
    {
      id: 'ra-001',
      volunteerName: 'Ananya Krishnan',
      volunteerEmail: 'ananya.k@gmail.com',
      volunteerAvatar: 'AK',
      programTitle: 'Digital Literacy Camp',
      programCategory: 'Tech',
      appliedDate: '2026-07-02',
      status: 'pending',
    },
    {
      id: 'ra-002',
      volunteerName: 'Vikram Patel',
      volunteerEmail: 'vikram.patel@yahoo.com',
      volunteerAvatar: 'VP',
      programTitle: 'Urban Reforestation Drive',
      programCategory: 'Environment',
      appliedDate: '2026-07-02',
      status: 'pending',
    },
    {
      id: 'ra-003',
      volunteerName: 'Shreya Iyer',
      volunteerEmail: 'shreya.iyer@outlook.com',
      volunteerAvatar: 'SI',
      programTitle: 'Youth Coding Bootcamp',
      programCategory: 'Tech',
      appliedDate: '2026-07-01',
      status: 'under_review',
    },
    {
      id: 'ra-004',
      volunteerName: 'Mohammed Rizwan',
      volunteerEmail: 'rizwan.m@gmail.com',
      volunteerAvatar: 'MR',
      programTitle: 'Clean River Initiative',
      programCategory: 'Environment',
      appliedDate: '2026-07-01',
      status: 'approved',
    },
    {
      id: 'ra-005',
      volunteerName: 'Pooja Desai',
      volunteerEmail: 'pooja.desai@gmail.com',
      volunteerAvatar: 'PD',
      programTitle: 'Women Empowerment Workshop',
      programCategory: 'Community',
      appliedDate: '2026-06-30',
      status: 'approved',
    },
    {
      id: 'ra-006',
      volunteerName: 'Karan Malhotra',
      volunteerEmail: 'karan.m@protonmail.com',
      volunteerAvatar: 'KM',
      programTitle: 'Mobile Health Clinic',
      programCategory: 'Health',
      appliedDate: '2026-06-30',
      status: 'rejected',
    },
    {
      id: 'ra-007',
      volunteerName: 'Divya Sharma',
      volunteerEmail: 'divya.sharma@gmail.com',
      volunteerAvatar: 'DS',
      programTitle: 'Digital Literacy Camp',
      programCategory: 'Tech',
      appliedDate: '2026-06-29',
      status: 'approved',
    },
    {
      id: 'ra-008',
      volunteerName: 'Ravi Teja',
      volunteerEmail: 'ravi.teja@gmail.com',
      volunteerAvatar: 'RT',
      programTitle: 'Youth Coding Bootcamp',
      programCategory: 'Tech',
      appliedDate: '2026-06-28',
      status: 'waitlisted',
    },
    {
      id: 'ra-009',
      volunteerName: 'Meera Subramaniam',
      volunteerEmail: 'meera.sub@gmail.com',
      volunteerAvatar: 'MS',
      programTitle: 'Urban Reforestation Drive',
      programCategory: 'Environment',
      appliedDate: '2026-06-27',
      status: 'approved',
    },
    {
      id: 'ra-010',
      volunteerName: 'Aakash Gupta',
      volunteerEmail: 'aakash.gupta@gmail.com',
      volunteerAvatar: 'AG',
      programTitle: 'Clean River Initiative',
      programCategory: 'Environment',
      appliedDate: '2026-06-26',
      status: 'under_review',
    },
  ],
};

/* ------------------------------------------------------------------ */
/*  ADMIN — ATTENDANCE STATS                                          */
/* ------------------------------------------------------------------ */
export const adminAttendanceStats = {
  todayPresent: 68,
  todayAbsent: 12,
  lateCheckIns: 7,
  programsRunning: 4,
  totalHoursToday: 272,
  attendancePercent: 82,
  recentActivity: [
    {
      id: 'aa-001',
      volunteerName: 'Ananya Krishnan',
      volunteerAvatar: 'AK',
      programTitle: 'Digital Literacy Camp',
      action: 'Checked In',
      time: '09:02 AM',
      location: 'Sanganer Village School',
      status: 'present',
    },
    {
      id: 'aa-002',
      volunteerName: 'Vikram Patel',
      volunteerAvatar: 'VP',
      programTitle: 'Urban Reforestation Drive',
      action: 'Checked In',
      time: '06:34 AM',
      location: 'Tilak Nagar Park',
      status: 'present',
    },
    {
      id: 'aa-003',
      volunteerName: 'Shreya Iyer',
      volunteerAvatar: 'SI',
      programTitle: 'Youth Coding Bootcamp',
      action: 'Checked In',
      time: '10:22 AM',
      location: 'Dharavi Community Centre',
      status: 'late',
    },
    {
      id: 'aa-004',
      volunteerName: 'Ravi Teja',
      volunteerAvatar: 'RT',
      programTitle: 'Youth Coding Bootcamp',
      action: 'Checked Out',
      time: '02:01 PM',
      location: 'Dharavi Community Centre',
      status: 'present',
    },
    {
      id: 'aa-005',
      volunteerName: 'Pooja Desai',
      volunteerAvatar: 'PD',
      programTitle: 'Women Empowerment Workshop',
      action: 'Checked In',
      time: '09:58 AM',
      location: 'Mehdipatnam Community Hall',
      status: 'present',
    },
    {
      id: 'aa-006',
      volunteerName: 'Mohammed Rizwan',
      volunteerAvatar: 'MR',
      programTitle: 'Clean River Initiative',
      action: 'Checked In',
      time: '07:00 AM',
      location: 'Sabarmati Riverfront, Gate 3',
      status: 'present',
    },
    {
      id: 'aa-007',
      volunteerName: 'Karan Malhotra',
      volunteerAvatar: 'KM',
      programTitle: 'Digital Literacy Camp',
      action: 'Marked Absent',
      time: '09:30 AM',
      location: 'Chomu Block Panchayat Hall',
      status: 'absent',
    },
    {
      id: 'aa-008',
      volunteerName: 'Divya Sharma',
      volunteerAvatar: 'DS',
      programTitle: 'Urban Reforestation Drive',
      action: 'Checked In',
      time: '06:30 AM',
      location: 'Tilak Nagar Park',
      status: 'present',
    },
    {
      id: 'aa-009',
      volunteerName: 'Meera Subramaniam',
      volunteerAvatar: 'MS',
      programTitle: 'Clean River Initiative',
      action: 'Checked Out',
      time: '10:08 AM',
      location: 'Sabarmati Riverfront, Gate 1',
      status: 'present',
    },
    {
      id: 'aa-010',
      volunteerName: 'Aakash Gupta',
      volunteerAvatar: 'AG',
      programTitle: 'Digital Literacy Camp',
      action: 'Checked In',
      time: '09:05 AM',
      location: 'Sanganer Village School',
      status: 'late',
    },
  ],
};

/* ------------------------------------------------------------------ */
/*  DEFAULT EXPORT                                                     */
/* ------------------------------------------------------------------ */
const mockData = {
  programs,
  applications,
  joinedPrograms,
  attendanceRecords,
  volunteerHoursStats,
  adminApplicationStats,
  adminAttendanceStats,
};

export default mockData;
